package view;

public class MainWind extends javax.swing.JFrame {
    
    // Variables declaration - do not modify                     
    private  ResultsPanel resultsPanel;
    private javax.swing.JLabel jLabelsubtitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFondo;
    
    // End of variables declaration      
    /**
     * Creates new form MainWindow
     */
    public MainWind() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        setResizable(false);
        
        resultsPanel= new ResultsPanel();
        jPanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelsubtitle = new javax.swing.JLabel();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NaviShip");

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        
        jPanelFondo.add(new ControlsPanel(resultsPanel), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 720));

        jPanel1.setBackground(new java.awt.Color(69, 123, 157));

        jLabelsubtitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelsubtitle.setForeground(new java.awt.Color(241, 250, 238));
        jLabelsubtitle.setText(" Barcos de Motor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jLabelsubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelsubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 810, 110));

        
        jPanelFondo.add(resultsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 810, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

                                                 

    /**
     * @param args the command line arguments
     */
    

                 
}